version: '3.3'
services:
  app-dev:
    # image: mcr.microsoft.com/devcontainers/rust
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      DATABASE_URL: "postgresql://root@roach1:26257/defaultdb?sslmode=disable"
      CARGO_TARGET_DIR: "/tmp/target"
      LANG: ja_JP.utf8
      LC_CTYPE: ja_JP.utf8
      DEBIAN_FRONTEND: noninteractive
    env_file: devcontainer.env
    depends_on:
      - cockroachdb_1
    networks:
      - roachnet

  cockroachdb_1:
    image: cockroachdb/cockroach:latest
    container_name: roach1
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - roachnet
    restart: always
    command: start-single-node --insecure
    volumes:
      - "./tmp/cockroach-data/roach1:/cockroach/cockroach-data"
networks:
  roachnet:
    driver: bridge
